# Generated by Django 3.1.3 on 2020-11-14 00:58

from django.db import migrations, models
import django.db.models.deletion
import notes.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('importance', notes.fields.IntegerRangeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='profiles.profile')),
                ('recipent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipent', to='profiles.profile')),
            ],
        ),
    ]
