# Generated by Django 3.1.3 on 2020-11-14 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='recipent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipent', to='profiles.profile'),
        ),
    ]
