# Generated by Django 3.1.3 on 2020-11-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('notes', '0002_auto_20201114_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='recipent',
        ),
        migrations.AddField(
            model_name='note',
            name='recipent',
            field=models.ManyToManyField(related_name='recipent', to='profiles.Profile'),
        ),
    ]
