# Generated by Django 3.1.3 on 2020-11-14 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('notes', '0003_auto_20201114_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='recipent',
        ),
        migrations.AddField(
            model_name='note',
            name='recipent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipent', to='profiles.profile'),
        ),
    ]
